server:
  port: 8080
  servlet:
    contextPath: /fibonacci
    session:
      cookie:
        name: App_${spring.application.name}
      timeout: 180m

spring:
  profiles:
    active: Production
  application:
    name: Fibonatchi
  jpa:
    hibernate:
      ddl-auto: update


---

spring:
  profiles: Production
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
    jpa:
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

---
spring:
  profiles: Development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
    jpa:
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true