version: '2'
services:
  demo-app:
    image: demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=Development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-postgresql:5432/postgres
    ports:
      - 8080:8080
  demo-postgresql:
    extends:
      file: postgresql.yml
      service: demo-postgresql
