version: '2'
services:
  demo-app:
    image: demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=Development
      - SPRING_DATASOURCE_URL=jdbc:mysql://demo-mysql:3306/springbootdb
    ports:
      - 8080:8080
  demo-mysql:
    extends:
      file: mysql.yml
      service: demo-mysql
