version: '2'
services:
  demo-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/demo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
